name        : bison
version     : 2.7
release     : 2
source      :
    - http://ftp.gnu.org/gnu/bison/bison-2.7.tar.gz : 19bbe7374fd602f7a6654c131c21a15aebdc06cc89493e8ff250cb7f9ed0a831
homepage    : http://www.gnu.org/software/bison
license     :
    - GPLv2+
summary     : General purpose parser generator
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
devel       : yes
description : |
    Bison is a general-purpose parser generator that converts an annotated context-free grammar into a deterministic LR or generalized LR (GLR) parser employing LALR(1) parser tables. As an experimental feature, Bison can also generate IELR(1) or canonical LR(1) parser tables. It is upward compatible with Yacc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %make clean
