name       : bison
version    : 3.3.2
release    : 9
source     :
    - https://ftp.gnu.org/gnu/bison/bison-3.3.2.tar.xz : 039ee45b61d95e5003e7e8376f9080001b4066ff357bde271b7faace53b9d804
homepage   : https://www.gnu.org/software/bison/
license    : GPL-3.0-or-later
component  : system.devel
summary    : General purpose parser generator
description: |
    Bison is a general-purpose parser generator that converts an annotated context-free grammar into a deterministic LR or generalized LR (GLR) parser employing LALR(1) parser tables. As an experimental feature, Bison can also generate IELR(1) or canonical LR(1) parser tables. It is upward compatible with Yacc
emul32     : yes
devel      : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
