name       : bison
version    : 3.2.4
release    : 7
source     :
    - https://ftp.gnu.org/gnu/bison/bison-3.2.4.tar.xz : 523d44419f4df68286503740c95c7b3400b748d7d8b797209195ee5d67f05634
homepage   : https://www.gnu.org/software/bison/
license    : GPL-3.0-or-later
component  : system.devel
summary    : General purpose parser generator
description: |
    Bison is a general-purpose parser generator that converts an annotated context-free grammar into a deterministic LR or generalized LR (GLR) parser employing LALR(1) parser tables. As an experimental feature, Bison can also generate IELR(1) or canonical LR(1) parser tables. It is upward compatible with Yacc
emul32     : yes
devel      : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
