name       : bison
version    : 3.0.4
release    : 6
source     :
    - https://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.xz : a72428c7917bdf9fa93cb8181c971b6e22834125848cf1d03ce10b1bb0716fe1
homepage   : http://www.gnu.org/software/bison
license    :
    - GPL-3.0
summary    : General purpose parser generator
component  : system.devel
emul32     : yes
devel      : yes
description: |
    Bison is a general-purpose parser generator that converts an annotated context-free grammar into a deterministic LR or generalized LR (GLR) parser employing LALR(1) parser tables. As an experimental feature, Bison can also generate IELR(1) or canonical LR(1) parser tables. It is upward compatible with Yacc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
