name       : bison
version    : 3.5.2
release    : 14
source     :
    - https://ftp.gnu.org/gnu/bison/bison-3.5.2.tar.xz : 24e273db9eb6da8bbb6f0648284d0724a5cbd6268a163db402f961350a4e50dd
homepage   : https://www.gnu.org/software/bison/
license    : GPL-3.0-or-later
component  : system.devel
summary    : General purpose parser generator
description: |
    Bison is a general-purpose parser generator that converts an annotated context-free grammar into a deterministic LR or generalized LR (GLR) parser employing LALR(1) parser tables. As an experimental feature, Bison can also generate IELR(1) or canonical LR(1) parser tables. It is upward compatible with Yacc
emul32     : yes
devel      : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check -j1
