name       : bison
version    : 3.6.2
release    : 18
source     :
    - https://ftp.gnu.org/gnu/bison/bison-3.6.2.tar.xz : 4a164b5cc971b896ce976bf4b624fab7279e0729cf983a5135df7e4df0970f6e
homepage   : https://www.gnu.org/software/bison/
license    : GPL-3.0-or-later
component  : system.devel
summary    : General purpose parser generator
description: |
    Bison is a general-purpose parser generator that converts an annotated context-free grammar into a deterministic LR or generalized LR (GLR) parser employing LALR(1) parser tables. As an experimental feature, Bison can also generate IELR(1) or canonical LR(1) parser tables. It is upward compatible with Yacc
emul32     : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check -j1
