name       : bison
version    : '3.5'
release    : 13
source     :
    - https://ftp.gnu.org/gnu/bison/bison-3.5.tar.xz : 55e4a023b1b4ad19095a5f8279f0dc048fa29f970759cea83224a6d5e7a3a641
homepage   : https://www.gnu.org/software/bison/
license    : GPL-3.0-or-later
component  : system.devel
summary    : General purpose parser generator
description: |
    Bison is a general-purpose parser generator that converts an annotated context-free grammar into a deterministic LR or generalized LR (GLR) parser employing LALR(1) parser tables. As an experimental feature, Bison can also generate IELR(1) or canonical LR(1) parser tables. It is upward compatible with Yacc
emul32     : yes
devel      : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check -j1
