name       : bison
version    : 3.7.2
release    : 19
source     :
    - https://ftp.gnu.org/gnu/bison/bison-3.7.2.tar.xz : 7948d193104d979c0fb0294a1854c73c89d72ae41acfc081826142578a78a91b
homepage   : https://www.gnu.org/software/bison/
license    : GPL-3.0-or-later
component  : system.devel
summary    : General purpose parser generator
description: |
    Bison is a general-purpose parser generator that converts an annotated context-free grammar into a deterministic LR or generalized LR (GLR) parser employing LALR(1) parser tables. As an experimental feature, Bison can also generate IELR(1) or canonical LR(1) parser tables. It is upward compatible with Yacc
emul32     : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check -j1
